# Exported from Render on 2024-05-27T23:43:31Z
services:
- type: web
  name: Articles
  runtime: docker
  repo: https://github.com/DIGORACCOON4279/Articles
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
